services:
  - type: web
    name: kho-my-pham
    env: python
    buildCommand: pip install -r requirements_production.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn kho_my_pham.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: kho_my_pham.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: khomypham.onrender.com
      # Set DATABASE_URL in Render Dashboard (Environment tab). Do not hard-code here.