# Generated by Django 5.2.4 on 2025-08-01 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Mã lô')),
                ('import_date', models.DateField(verbose_name='Ngày nhập')),
                ('import_quantity', models.IntegerField(verbose_name='Số lượng nhập')),
                ('remaining_quantity', models.IntegerField(verbose_name='Số lượng còn lại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Lô hàng',
                'verbose_name_plural': 'Lô hàng',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu xuất')),
                ('export_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày xuất')),
                ('customer', models.CharField(blank=True, max_length=200, verbose_name='Khách hàng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
                'ordering': ['-export_date'],
            },
        ),
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giảm giá (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch', verbose_name='Lô hàng')),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.export', verbose_name='Phiếu xuất')),
            ],
            options={
                'verbose_name': 'Chi tiết xuất kho',
                'verbose_name_plural': 'Chi tiết xuất kho',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu nhập')),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Nhà cung cấp')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.import', verbose_name='Phiếu nhập')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết nhập kho',
                'verbose_name_plural': 'Chi tiết nhập kho',
            },
        ),
    ]
