# Generated by Django 5.2.4 on 2025-08-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_expiry_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_days',
        ),
    ]
